# Site settings
author: Janae Quinones
title: Janae's Blog
header-img: img/home-bg.png
email: janaemassa@gmail.com
copyright_name: Janae Quinones
description: > # this means to ignore newlines until "baseurl:"
  Blog posts from Flatiron
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: janaaeeee
github_username:  Janaeq

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
